### ISSUE TITLE
MicroOp

### ISSUE THREAD

**Issue by PAEz** [andrejewski/himalaya#1]
Just flicking through ya code and noticed this line...
https://github.com/andrejewski/himalaya/blob/master/index.js#L42
`if(!str.indexOf(commentStart)) {`
I take it that line is checking to see if str starts with commentStart.  Well I just wanted to point out that thats the slowest way of doing it (by alot).  Check this....
https://jsperf.com/string-startswith/25
..notice the last test?  might be ugly but the speed increases are huge.  Used it once myself and made a huge difference.  Use to be the lastIndexOf won (besides being hardcoded), was surprised to see slice and substring winning.

While Im here....
Those `!str.indexOf`,`!~`,etc are real clever and all but hard to know whats going on.  I had to run tests in the console to figure it out as what the hell do ya google?

**Comment by andrejewski** [comment]
I feel you. The performance is pretty bad using indexOf, but I have been using these for a long time because there was no `startsWith()`, `endsWith()`, or `contains()` methods on String. That is changing with ES6 (though `contains()` is `includes()` for backwards compatibility).

The native implementations will win on performance and be much more readable. These have already dropped in Chrome so (with the just announced merger between io.js and the core project) these should be coming to Node.js soon.

In the meantime and for older versions of Node, we should switch over to the hard coded check. This type of check is only done 3 times throughout and with small, fixed size strings so it's only slightly ugly.

Thanks for the catch and the perf info!
