### ISSUE TITLE
Create TypeScript type definitions

### ISSUE THREAD

**Issue by dbautistav** [andrejewski/himalaya#23]
Create TypeScript type definitions for this project to being able to use it in projects written in TypeScript.

**Comment by andrejewski** [comment]
This at the moment seems reasonable. When I have time to investigate further, I will work on this. If you have your own workaround definitions, please open a PR if only to give me a good starting point for introducing Typescript. Thank you for raising this issue.

**Comment by andrejewski** [comment]
I turned out to not want to do this. Here is my reasoning:

- I don't know or use TypeScript so I don't feel comfortable maintaining something in it for other people to use
- The set of methods exported is small, so writing your own definitions can't be too hard
- As far as writing type definitions for the AST, things might get messy when we start adding new AST versions in the future

Closing because I'd need a co-maintainer fluent in TypeScript to support this.
