### ISSUE TITLE
(Suggestion) Consider changing the attributes property from an Object to an Array

### ISSUE THREAD

**Issue by themaxsandelin** [andrejewski/himalaya#44]
If you did change the attributes property from an Object to an Array, it would make it much easier to loop through and check the content length. This is especially useful when dynamically building elements using `document.createElement()`. 👌🏻

**Comment by andrejewski** [comment]
@themaxsandelin Himalaya conforms to a [spec](https://github.com/andrejewski/himalaya/blob/master/text/ast-spec-v0.md) so I can't change the format without a huge breaking change.

That spec was written with many niceties/preprocessing included as that was what I wanted at the time. However, there are now many things I'd like to fix about the spec like what you mention. Under the hood, Himalaya is written with new specs in mind so this will not take much work. When I sit down to write a new spec (potentially for v1.0), this will be incorporated.

I'm closing this issue because we're on the same page. This issue will be addressed in some future version, but until then in your case `Object.keys()` is a good enough workaround.
