### ISSUE TITLE
how to use in html page with node.js server

### ISSUE THREAD

**Issue by techashish12** [andrejewski/himalaya#46]

**Comment by andrejewski** [comment]
This issue is vague; I will explain based on what I think you mean:

**You want to run Himalaya in a web browser**
Himalaya can be used in any webpage just download this [script](https://github.com/andrejewski/himalaya/blob/4aeb11b45d1ab065ff9a6c47e1051de5a0335b54/docs/dist/himalaya.js) and link to it in your webpage, it will expose as `window.himalaya`.

**You want to run Himalaya server-side and send results to a web browser**
Himalaya is just a Node module, so `require()` it and use it with a web server (Express, Koa).

If you meant a different thing, let me know; otherwise, close this issue.
