### ISSUE TITLE
Don't force lowercase on anchors

### ISSUE THREAD

**Issue by snajjar** [andrejewski/himalaya#55]
Hello,

First, I would like to thank you for this awesome library. Works great.

I would like to add support for camel-cased anchors, which is useful for special HTML templating systems.
Right now, if we put camel case in HTML, himalaya cut it down to lower case:

    var himalaya = require('himalaya');
    var toHTML = require('himalaya/translate').toHTML;
    toHTML( himalaya.parse('<div><specialAnchor><specialValue1>1</specialValue1><specialValue2>2</specialValue2></div>') )
    // returns "<div><specialanchor><specialvalue1>1</specialvalue1><specialvalue2>2</specialvalue2></specialanchor></div>"

Since JSON supports (and use) camelCase, i think himalaya should provide an option to support it.
From looking into the source, it seems that this line is the problem:

    const tagName = tagToken.content.toLowerCase() // parser.js:44

Since HTML supports uppercase for anchors, I think himalaya should return exactly what was parsed through `toHTML(himalaya.parse(someString))`

    toHTML( himalaya.parse('<P>some text</P>') )
    // returns '<p>some text</p>' but should return '<P>some text</P>'

What's your opinion about this? Is there another reason justifying the forced lower case on anchors?

**Comment by andrejewski** [comment]
Himalaya is aligned with the HTML5 specification as much as possible. In HTML5, and all previous HTML versions, [tag names are case insensitive](https://www.w3.org/TR/2012/WD-html-markup-20120315/documents.html#case-insensitivity). When parsing tag names, Himalaya lowercases them so they can be compared.

The reason the output is also lowercase is really about removing developer error. Inspecting and manipulating the JSON output would be more tedious if you had to account for all case-insensitive variants yourself, which I can understand *wanting* to do. Since in HTML there is no semantic difference, it's probably not best to build your logic around case sensitivity as any transformation step along the way (like Himalaya) may not respect it.

I don't think I will change my mind on this decision. Maybe in future AST specifications we can record the literal tag start and end names to node fields, but that is a large undertaking I don't have time for at the moment.

*Aside:* Most templating languages I see use `component-name` instead of `componentName` for tags. This is inline with the specification for Web Components, which to many is the future of the web. Some templating/view libraries make the mistake of trying to make HTML case sensitive and it gets ugly fast as you need an imperfect serialization step which leaves something looking unreadable. I do not recommend building along that road.

**Comment by snajjar** [comment]
Thank you for your quick reaction. I was kinda expecting this.
Yours recommandations make sense, but in this scenario, unfortunately, my hands are tied.
I'll figure something out. Thank you for your time and for this nice library :)
