### ISSUE TITLE
 inlineStyle and serializeAttr in translate.js has some errors

### ISSUE THREAD

**Issue by longjiarun** [andrejewski/himalaya#61]
I input the AST tree that has been transformed
```
{
    "type": "Element",
    "tagName": "body",
    "children": [
        {
            "type": "Element",
            "tagName": "view",
            "attributes": {
                "className": [
                    "div"
                ]
            },
            "children": [
                {
                    "type": "Text",
                    "content": "\n    &lt;     &gt; a ' \" &amp;  \n    "
                }
            ]
        }
    ]
}

```
then i get the error 

```
TypeError: Cannot convert undefined or null to object
    at inlineStyle (/projec_root/node_modules/himalaya/lib/translate.js:38:17)
```
happen in  inlineStyle function
```
function inlineStyle(style) {
  return Object.keys(style).reduce(function (css, key) {
    return css + '; ' + dasherize(key) + ': ' + style[key];
  }, '').slice(2);
}
```
and serializeAttr also has some problem if value is null or undefined
```
function serializeAttr(attr, value, isXml) {
  if (!isXml && attr === value) return attr;

  try{
    console.log(value)
    //-------------- here 
    var text = value.toString();
  
    var quoteEscape = text.indexOf('\'') !== -1;
    var quote = quoteEscape ? '"' : '\'';
    return attr + '=' + quote + text + quote;
  }catch(e){
    console.log(value)
    console.log(e)
  }
  return ''
}

```

**Comment by longjiarun** [comment]
I use himalaya in project, so  I'm waiting for fix issues. Thank you for you fix.

**Comment by andrejewski** [comment]
I took your example and tried it with latest Himalaya.

```js
const translate = require('himalaya/lib/translate')
const j = {
    "type": "Element",
    "tagName": "body",
    "children": [
        {
            "type": "Element",
            "tagName": "view",
            "attributes": {
                "className": [
                    "div"
                ]
            },
            "children": [
                {
                    "type": "Text",
                    "content": "\n    &lt;     &gt; a ' \" &amp;  \n    "
                }
            ]
        }
    ]
}
translate.toHTML(j)
// => <body><view class=\'div\'>\n    &lt;     &gt; a \' " &amp;  \n    </view></body>
```

Following the [specification for attributes](https://github.com/andrejewski/himalaya/blob/14fd2d5e7fc6e919bb5d0ffa3157318468d72f52/text/ast-spec-v0.md#attributes), Himalaya attribute values will never be `null` or `undefined` so it is technically safe for us to make the assumption. If you are doing any intermediate processing of the parsed JSON, you need to properly remove values (use `delete o.key`, not `o.key = undefined`) so that your changes also align with the spec.

Also, I will clarify that consumers of this library should not rely on or use `inlineStyle` or `serializeAttr` in their code. They are exported for testing, but not guaranteed by any SemVer/spec.

If you can provide the original HTML that caused these errors and haven't done any intermediate processing, please re-open this issue.

**Comment by longjiarun** [comment]
Sorry, It's my fault. 
I set the value to  `undefined`, when transform the JSON.
Thanks for you reply.
