### ISSUE TITLE
Couldn't find preset "es2015" using react native

### ISSUE THREAD

**Issue by JorgeCeja** [andrejewski/himalaya#65]
Hello, I'm trying to use this package with react native v48.4, but I ran into this issue. I am open to help out if possible.

**Comment by andrejewski** [comment]
It sounds like you are trying to build Himalaya, which you should not need to. Himalaya is tested all the way back to Node 4 so using it straight after doing `npm install himalaya` should be fine.

**Comment by JorgeCeja** [comment]
ok, I will take a look at it and I'm close the issue. Thanks!

**Comment by mauricekleine** [comment]
@JorgeCeja what did you do to solve this? I'm experiencing the same problem in an app created with Create React Native app.

**Comment by JorgeCeja** [comment]
@mauricekleine I ended up using [react-native-cheerio](https://www.npmjs.com/package/react-native-cheerio)

**Comment by andrejewski** [comment]
@JorgeCeja I'm really sorry to hear that. @mauricekleine do you have a reproducible case? I still think this is a build problem because React Native shouldn't be digging into how Himalaya is built. Himalaya only has `devDependencies` so it is concerning multiple people are seeing this. I'd expect other packages to be having this problem as well.

**Comment by mauricekleine** [comment]
@andrejewski you should be able to reproduce it by running Create React Native App and adding Himalaya as a dependency. I haven't come across this problem before, but that's because I mostly use packages that are optimised for React Native. I guess that RN does indeed dig into how Himalaya is built, although I'm not sure how. I'll let you know if I find something.

**Comment by andrejewski** [comment]
I can't reproduce myself, please provide a sample.

I took the following steps:

```sh
create-react-native-app Test
cd Test
yarn add himalaya
```

Added an import to the `App.js`:

```js
import React from 'react';
import { StyleSheet, Text, View } from 'react-native';
import { parse } from 'himalaya';

export default class App extends React.Component {
  render() {
    return (
      <View style={styles.container}>
        <Text>Open up App.js to start working on your app!</Text>
        <Text>Changes you make will automatically reload.</Text>
        <Text>Shake your phone to open the developer menu.</Text>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});
```

Ran `yarn start` and opened the app on my phone in Expo, the build was successful.

---

I see mention online of how removing your `.babelrc` file may fix this, or may forking himalaya and removing the mention of the preset in the package.json. If we find a solution here, I recommend opening an issue against React Native as this is their bug.

**Comment by mauricekleine** [comment]
@andrejewski thanks for looking into it. I followed your steps and indeed, it works. My app uses react-native 0.49.X, whereas a clean install with create-react-native-app uses react-native 0.50.X. Upgrading my app to RN 0.50.X does result in the build succeeding with Himalaya imported, so upgrading to RN >0.50 should fix this problem.
