### ISSUE TITLE
Problem with attribute name

### ISSUE THREAD

**Issue by pahan40** [andrejewski/himalaya#67]
Hello. I am having a problem with trying to convert json to html obly with inputs and it's attribute name.
For Example, I translate html to json 
`<input type="text" name="name"> `
and I got this json
```
[
  {
    "type": "Element",
    "tagName": "input",
    "attributes": {
      "type": "text",
      "name": "name"
    },
    "children": []
  }
]
```

But When I try to translate this json to HTML I got something like this

`<input type='text' name>`

As you see attribute name lost it value. Could you help me to fix this issue  ?
Thank you.

**Comment by andrejewski** [comment]
This is inline with the [`v0` specification](https://github.com/andrejewski/himalaya/blob/master/text/ast-spec-v0.md), which has many problems that will be addressed in a new specification.

Any attribute with the same value and the name is "condensed" to just the attribute. This made some sense for attributes like "disabled" but certainly not "name". Instead of defying the spec and potentially breaking current users, I suggest waiting for this new specification. In the meantime you can replace `"name"` in the JSON with `"name{randomCharacters}"` so it's not lost and then undo that on the HTML output. This is definitely not ideal, and I am sorry. The v0 spec was poorly designed.

**Comment by andrejewski** [comment]
I just released [`v1`](https://github.com/andrejewski/himalaya/blob/master/text/ast-spec-v1.md) which will parse the `name` attribute correctly, please refer to the README on how to leverage that format today.
