### ISSUE TITLE
JSON

### ISSUE THREAD

**Issue by pkoppstein** [andrejewski/himalaya#83]
Himalaya is neat, but its output is not strictly JSON. Or rather, the output of parse(html) is not JSON.

It is of course easy enough to write JSON.stringify(parse(html)) but then the pretty-printing is lost. That too can be overcome, but I was thinking that since Himalaya is advertised as producing JSON, maybe I'm missing something...

Thank you.

**Comment by andrejewski** [comment]
You are correct that Himalaya does not output a string of JSON. I'll explain some of the reasoning behind the decisions here, others will find this useful I'm sure.

**Why call it "HTML to JSON"?**
JSON is more universally known than POJO (Plain Old JavaScript Object). POJO would probably be the better term but that is overloaded with "Plain Old Java Object" from Java. JSON is stricter than JS POJOs as I don't know if/how new ES6 features like Symbols qualify as part of a JS object that someone would call a POJO. The language is muddled, so JSON is our best descriptor and the best keyword for people searching for tools as JSON is cross-language and in JS the conversion to a JSON string is so easy. People using different languages often create small Node scripts that call Himalaya and pipe the result back to their program. Calling it JSON helps people not have to reinvent the wheel in their own languages without having to be in-the-know of JavaScript terminology.

**Why not produce a JSON string?**
Himalaya is a utility to parse HTML into JSON to be more easily *manipulated by other modules*. Most people use Himalaya to parse and then do data manipulation with the result. Serializing to JSON only for people to have to parse it back into POJOs is odd and also not performant for very huge strings of HTML. The other problem is stringification, `JSON.stringify` accepts options for how to format JSON (like pretty printing). Rather than have Himalaya accept the same options, we make the user decide how to stringify their POJOs. This is good for Himalaya as it means less code to support and good for JavaScript developers because they do not need to learn new APIs and can leverage existing knowledge.

A lot of effort has been put into making Himalaya do as little as possible. I think making very few assumptions about what users intend to do and having a very small API surface area are part of the reason why Himalaya has gotten so popular.

---

I am closing this issue. Please add a comment here if anything needs elaboration.

**Comment by pkoppstein** [comment]
@andrejewski - Thanks for the detailed response, which leads to the following two enhancement requests:

1. provide a javascript function to perform the conversion, along the lines of:

    JSON.stringify(parse(html), null, 2))  

2. provide a shell command (like easyconvert's `easyconvert`) that really would convert HTML to JSON

 See https://www.npmjs.com/package/easyconvert

**Comment by andrejewski** [comment]
@pkoppstein 

Adding feature 1 would go against doing as little as possible. That feature won't be added.

Adding feature 2 is out of project scope. There was in pre-v1.0 a CLI tool for converting HTML and JSON back and forth, but it was not used enough and didn't have proper tests. Someone can create a fully featured `himalaya-cli` package if they would like. I don't have the time.

**Comment by pkoppstein** [comment]
@andrejewski - Feature 1 is necessary for truth in advertising, unless you change the claim to refer to "JSO" instead of JSON, which would be a reasonable thing to do, though implementing (1) would be trivial.  

Implementing (2) robustly would require some work, but maybe good enough would be good enough.  Would you be prepared to accept a cli.js addition?

**Comment by andrejewski** [comment]
If you are interested in creating a CLI, please create a new package.
