### ISSUE TITLE
Invalid parsing for non-tags

### ISSUE THREAD

**Issue by umbrella-anton-karmazin** [andrejewski/himalaya#92]
```
<a href="link">I <3 NY, dude</a>.
```

will be parsed as 

```
[
  {
    "type": "element",
    "tagName": "a",
    "attributes": [
      {
        "key": "href",
        "value": "link"
      }
    ],
    "children": [
      {
        "type": "text",
        "content": "I"
      },
      {
        "type": "element",
        "tagName": "3",
        "attributes": [
          {
            "key": "NY,",
            "value": null
          },
          {
            "key": "dude",
            "value": null
          }
        ],
        "children": []
      },
      {
        "type": "text",
        "content": ">."
      }
    ]
  }
]
```

I understand that `<3` should be escaped, but sometimes we cannot manage content pre-processing. Any ideas, how can it be avoided?

**Comment by andrejewski** [comment]
Himalaya follows the HTML5 spec. In regard to tag names, [numbers are valid](https://www.w3.org/TR/2011/WD-html5-20110525/syntax.html#syntax-tag-name).

Although this project cannot help, I'll share some potential solutions I have experienced:

- Perform both a pre-processing and then post-processing step. If you are comfortable making the assumption that all submitted HTML tags should not begin with numbers, then you can do a regex replacement beforehand and then walk the parse tree after, converting content back.

- If this is a user facing application, allow the user to preview and/or test the result of the HTML parsing in some way. This feedback loop will allow them to remedy the problem.

- Accept the poorly formatted HTML, but log unusual patterns alongside the processing so that the original intent is maybe not perfectly captured, but is at least noticeable.

None of these solutions are perfect.
